rm head_1.d
rm head_2.d
rm head_3.d
rm head_4.d
rm head_5.d
rm head_6.d
rm investigated_1.d
rm investigated_2.d
rm investigated_3.d
rm investigated_4.d
rm investigated_5.d
rm investigated_6.d
rm covMatrix.txt
rm gelmanRubin.txt
rm progress.txt 
rm transfcmb_1.d
rm transfcmb_2.d
rm transfcmb_3.d
rm transfcmb_4.d
rm transfcmb_5.d
rm transfcmb_6.d
rm covfile_*
rm TEB_*.d
rm TT_*.d
rm check_test_*
rm test_*
rm TT_*.d.like
rm TEB_*.d.like
rm montecarlo_chain_*.d
rm montecarlo_chain_freeze_*.d
rm error.txt
rm output.txt
